### ISSUE TITLE
Analyze mouse 10x and SS2 mouse data: scRNAseqSystemicComparison

### ISSUE THREAD

**Issue by jychien** [HumanCellAtlas/secondary-analysis#817] opened 2019-10-11 17:25 UTC
The "scRNAseqSystemicComparison" mouse bundles are ready for secondary analysis.

**Project title:** Systematic comparative analysis of single cell RNA-sequencing methods
**Project short name:** scRNAseqSystemicComparison
**Project UUID:** 88ec040b-8705-4f77-8f41-f81e57632f7d
**Metadata:** mouse, 10x v2 and SS2
**Bundles:** 2 10x primary bundles; 1,536 SS2 primary bundles

https://tracker.data.humancellatlas.org/?projectUUID=88ec040b-8705-4f77-8f41-f81e57632f7d

@HumanCellAtlas/data-ops

**Comment by samanehsan** [comment] 2019-11-18 16:04
Duplicate of #843, which is closed

**Closed by samanehsan** 2019-11-18 16:04 UTC
Labels: data ops, infrastructure
